# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore MyLibrary.sln
    
    - name: Build the Solution
      run: msbuild MyLibrary.sln
    
    - name: Run Tests
      run: vstest.console.exe ./MyLibraryTests/bin/Debug/MyLibraryTests.dll /Logger:trx;LogFileName=TestLog.trx
    
    - name: TRX 2 Excel - CD
      run: cd ../
    
    - name: TRX 2 Excel - Clone
      run: git clone https://github.com/rahulrathore44/Trx2Excel.git
    
    - name: TRX 2 Excel - Produce Excel
      run: Trx2Excel/Trx2Excel/bin/Debug/Trx2Excel.exe D:\a\ConsoleUnitTests\ConsoleUnitTests\TestResults\TestLog.trx ./MyLibrary/bin/Debug/netstandard2.0/results.xlsx
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./MyLibrary/bin/Debug/netstandard2.0/
        asset_name: MyLibrary.dll
        asset_content_type: application/zip
      
      
    #- name: Upload a Build Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    # Artifact name
    #    name: GH-MiscToolbox
    #    # A file, directory or wildcard pattern that describes what to upload
    #    path: GH.MiscToolbox/GH.MiscToolbox/bin/GH.MiscToolbox.gha


